# Official Catppuccin Latte palette.
# https://github.com/catppuccin/catppuccin

set -g @thm_bg "#eff1f5"
set -g @thm_fg "#4c4f69"
set -g @thm_rosewater "#dc8a78"
set -g @thm_flamingo "#dd7878"
set -g @thm_pink "#ea76cb"
set -g @thm_mauve "#8839ef"
set -g @thm_red "#d20f39"
set -g @thm_maroon "#e64553"
set -g @thm_peach "#fe640b"
set -g @thm_yellow "#df8e1d"
set -g @thm_green "#40a02b"
set -g @thm_teal "#179299"
set -g @thm_sky "#04a5e5"
set -g @thm_sapphire "#209fb5"
set -g @thm_blue "#1e66f5"
set -g @thm_lavender "#7287fd"
set -g @thm_subtext_1 "#5c5f77"
set -g @thm_subtext_0 "#6c6f85"
set -g @thm_overlay_2 "#7c7f93"
set -g @thm_overlay_1 "#8c8fa1"
set -g @thm_overlay_0 "#9ca0b0"
set -g @thm_surface_2 "#acb0be"
set -g @thm_surface_1 "#bcc0cc"
set -g @thm_surface_0 "#ccd0da"
set -g @thm_mantle "#e6e9ef"
set -g @thm_crust "#dce0e8"
