description = "Stop current approach and reconsider the problem from scratch"
prompt = """
Stop current approach and reconsider the problem from scratch.

You need to immediately stop and completely dismiss your current approach. Take a step back and think about this problem with fresh eyes.

**Current approach assessment:**
- What assumptions might be incorrect?
- What constraints or requirements am I missing?
- Am I solving the right problem?
- What blind spots do I have?

**Required next steps:**
1. Acknowledge specifically what wasn't working about the previous approach
2. Identify at least 2-3 completely different angles to tackle this problem
3. Choose the most promising new direction based on the actual requirements
4. Start fresh with the new approach - don't try to salvage previous work

Think outside the box, approach this as if seeing the problem for the first time.
"""
