name: MyConfig
version: 0.0.1

models:
  - name: Cogito 8B
    provider: ollama
    model: cogito:8b
    roles: [chat, edit, apply]

  - name: Cogito 14B
    provider: ollama
    model: cogito:14b
    roles: [chat, edit, apply]

  - name: Qwen2.5 7B
    provider: ollama
    model: qwen2.5:7B
    roles: [chat, edit, apply]

  - name: Qwen2.5 14B
    provider: ollama
    model: qwen2.5:14b
    roles: [chat, edit, apply]

  - name: Qwen2.5 Coder 7B
    provider: ollama
    model: qwen2.5-coder:7b
    roles: [chat, edit, apply]

  - name: Qwen2.5 Coder 14B
    provider: ollama
    model: qwen2.5-coder:14b
    roles: [chat, edit, apply]

  - name: DeepSeek R1 14B
    provider: ollama
    model: deepseek-r1:14b
    roles: [chat, edit, apply]

  - name: Qwen2.5 Coder 1.5B base
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    roles: [autocomplete]

  - name: Qwen2.5 Coder 3B base
    provider: ollama
    model: qwen2.5-coder:3b-base
    roles: [autocomplete]

  - name: Qwen2.5 Coder 7B base
    provider: ollama
    model: qwen2.5-coder:7b-base
    roles: [autocomplete]

  - name: Nomic Embed v1.5
    provider: ollama
    model: nomic-embed-text:v1.5
    roles: [embed]

  - name: Ollama
    provider: ollama
    model: AUTODETECT

  - name: LM Studio
    provider: lmstudio
    model: AUTODETECT

context:
  - provider: file
  - provider: currentFile
  - provider: open
    params:
      onlyPinned: true
  - provider: tree
  - provider: code
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: search
  - provider: docs
  - provider: folder
  - provider: repo-map
    params:
      includeSignatures: false
  - provider: codebase

prompts:
  - name: explain
    description: Explain my code
    prompt: |
      Please read the highlighted code and explain it to me. You should look for the following, and be extremely vigilant:
        - What does this code do?
        - How does it work?
        - Why is it written this way?
        - What are the inputs and outputs?
        - What are the edge cases?
        - Anything else that looks important

      Once you find an answer, please explain it as clearly as possible, but without using extra words. For example, instead of saying 'I think this code is doing X', you should say 'This code is doing X'. Give your answer as one bullet point per explanation found.
  
  - name: check
    description: Check for mistakes in my code
    prompt: |
      Please read the highlighted code and check for any mistakes. You should look for the following, and be extremely vigilant:
        - Syntax errors
        - Logic errors
        - Security vulnerabilities
        - Performance issues
        - Anything else that looks wrong

      Once you find an error, please explain it as clearly as possible, but without using extra words. For example, instead of saying 'I think there is a syntax error on line 5', you should say 'Syntax error on line 5'. Give your answer as one bullet point per mistake found.
  
  - name: fix
    description: Fix the mistakes in my code
    prompt: |
      Please read the highlighted code and fix any mistakes. You should look for the following, and be extremely vigilant:
        - Syntax errors
        - Logic errors
        - Security vulnerabilities
        - Performance issues
        - Anything else that looks wrong

      Once you find an error, please explain it as clearly as possible, but without using extra words. For example, instead of saying 'I think there is a syntax error on line 5', you should say 'Syntax error on line 5'. Give your answer as one bullet point per mistake found.  

  - name: refactor
    description: Refactor my code
    prompt: |
      Please read the highlighted code and refactor it. You should look for the following, and be extremely vigilant:
        - Code smells
        - Duplicated code
        - Long methods
        - Long classes
        - Anything else that looks wrong

      Once you find an error, please explain it as clearly as possible, but without using extra words. For example, instead of saying 'I think there is a syntax error on line 5', you should say 'Syntax error on line 5'. Give your answer as one bullet point per mistake found.
  
  - name: test
    description: Write tests for my code
    prompt: |
      Please read the highlighted code and write tests for it. You should look for the following, and be extremely vigilant:
        - Unit tests
        - Integration tests
        - End-to-end tests
