name: minimal
version: 0.0.1

models:
  - name: Ollama
    provider: ollama
    model: AUTODETECT

  - name: LM Studio
    provider: lmstudio
    model: AUTODETECT

  - name: Qwen2.5 Coder 1.5B base
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    roles: [autocomplete]

  - name: Qwen2.5 Coder 3B base
    provider: ollama
    model: qwen2.5-coder:3b-base
    roles: [autocomplete]

  - name: Qwen2.5 Coder 7B base
    provider: ollama
    model: qwen2.5-coder:7b-base
    roles: [autocomplete]

  - name: Nomic Embed v1.5
    provider: ollama
    model: nomic-embed-text:v1.5
    roles: [embed]

context:
  - provider: file
  - provider: currentFile
  - provider: open
    params:
      onlyPinned: true
  - provider: tree
  - provider: code
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: search
  - provider: docs
  - provider: folder
  - provider: repo-map
    params:
      includeSignatures: false
  - provider: codebase

prompts:
  - name: check
    description: Check for mistakes in my code
    prompt: |
      Please read the highlighted code and check for any mistakes. You should look for the following, and be extremely vigilant:
        - Syntax errors
        - Logic errors
        - Security vulnerabilities
        - Performance issues
        - Anything else that looks wrong

      Once you find an error, please explain it as clearly as possible, but without using extra words. For example, instead of saying 'I think there is a syntax error on line 5', you should say 'Syntax error on line 5'. Give your answer as one bullet point per mistake found.
